sonar

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -5,15 +5,36 @@ on:
       - main
   pull_request:
     types: [opened, synchronize, reopened]
+
 jobs:
   sonarqube:
-    name: SonarQube
+    name: Sonar Scan 
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0  
+
       - name: SonarQube Scan
         uses: SonarSource/sonarqube-scan-action@v4
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          
+      # Check SonarCloud Quality Gate status
+      - name: Check Quality Gate status
+        run: |
+          # Make an API call to SonarCloud to get the Quality Gate status
+          result=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Calum-DC_frontend_microservice_applicaiton")
+          status=$(echo $result | jq -r '.projectStatus.status')
+          
+          # Check if the Quality Gate status is "OK" (success)
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate failed: $status"
+            exit 1  # Exit with status 1 to fail the job
+          else
+            echo "Quality Gate passed"
+          fi
+        continue-on-error: false 
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
